version: "3.9"
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - user-network

  mongodb:
    image: mongo:6
    container_name: user-mongo
    ports:
      - "27017:27017"
    networks:
      - user-network
    volumes:
      - mongo-data:/data/db

networks:
  user-network:

volumes:
  mongo-data:
